### ISSUE TITLE
Ruby - Capstone - Kanban board review

### ISSUE THREAD

**Issue by Rebelzob** [Rebelzob/catalog-of-my-things#38]
- Project [link](https://github.com/Rebelzob/catalog-of-my-things/projects/1)

- There are 4 people in the group
  - Team member 1: @Rebelzob 
  - Team member 2: @kambereBr 
  - Team member 3: @JavierAybar 
  - Team member 4: @diarisdiakite

**Comment by tresorsawasawa** [comment]
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Rebelzob, @kambereBr, @diarisdiakite, and @JavierAybar 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All requirements have their cards :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] As required for the project all your cards to have a description of the task, kindly ensure that you add a description of the task on the below card:
![image](https://github.com/Rebelzob/catalog-of-my-things/assets/83042742/95352653-2a3c-4c1a-b791-34e75e5e0281)

- [ ] As it is required for the project all your tasks to be distributed in a fair way, kindly ensure that no student has significantly (difference >= 5 points) more or less points than others. I suggest you check **[ points ]** of each one and ensure that there is no big difference as I mentioned here, fix it and ask again for a review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by LionRouge1** [comment]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- Add a description to all the cards :heavy_check_mark: 
- No student has significantly (difference >= 5 points) more or fewer points than others :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
